version: '3'
services:
  ros2-container:
    build: .
    image: ros2_humble_custom:latest
    network_mode: host
    volumes:
      - ../:/ros2_ws   # Maps host ./ros2_ws folder into container
      - /media/tdem-raspi/bag_folder:/ros2_ws/bag_folder   # Maps host ./ros2_ws folder into container
    environment:
      - ROS_DOMAIN_ID=0
      - ROS_LOCALHOST_ONLY=0
    stdin_open: true
    tty: true
    restart: always
    command: >
      bash -c "
        source /opt/ros/humble/setup.bash &&
        source /ros2_ws/install/setup.bash &&
        cd /ros2_ws/bag_folder &&
        ros2 bag record -a -b 5000000000
      "