version: '3.8'
services:
  ros2:
    build:
      context: .
      dockerfile: galactic.Dockerfile   # <-- use your custom file
      target: dev                       # <-- if your Dockerfile uses multi-stage builds
    image: ros2-galactic-dev
    network_mode: host
    container_name: ros2-galactic
    volumes:
      - ../:/ros2_ws    # Mount your local workspace into the container
    tty: true                 # Allocate a terminal
    environment:
      - TZ=Asia/Bangkok
      - ROS_DOMAIN_ID=5
      - ROS_LOCALHOST_ONLY=0
    command: bash             # Start with bash shell