on:
  pull_request:
    types: [opened, reopened, ready_for_review]
  issue_comment:
jobs:
  pr_agent_job:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Run pr agent on every pull request, respond to user comments
    steps:
      - name: PR Agent action step
        id: pragent
        uses: mhenPiyawut/pr-agent-optimizer@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI.API_TYPE: "azure"
          OPENAI.API_VERSION: ${{ secrets.AZURE_OPENAI_API_VERSION }}
          OPENAI.KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
          OPENAI.API_BASE: ${{ secrets.AZURE_OPENAI_API_BASE }}
          OPENAI.DEPLOYMENT_ID: "gpt-4.1-ts4-jpe"
          CONFIG.MODEL: "gpt-4.1-ts4-jpe"